baseURL: https://unthenamed.eu.org/
title: Unthenamed
theme: hugo-theme-bootstrap
copyright: '© {year} Unthenamed. All Rights Reserved.'
defaultContentLanguage: id
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages
# defaultContentLanguageInSubdir: true
disableLanguages:
  - fr
  - zh-cn
  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-Y27RW84NTH
disqusShortname: unthenamed

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  posts: /artikel/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn
